DROP TABLE TARGETA_CLIENTE CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE TICKET CASCADE CONSTRAINTS;
DROP TABLE LINEA_TICKET CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE STOCK_SUPERMERCADO CASCADE CONSTRAINTS;
DROP TABLE SUPERMERCADO CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE NOMINA CASCADE CONSTRAINTS;
DROP TABLE PLANTILLA_NOMINA CASCADE CONSTRAINTS;
DROP TABLE LINEA_CARRITO CASCADE CONSTRAINTS;

CREATE TABLE CLIENTE (  
DNI_Cliente VARCHAR(9) NOT NULL,
Nombre_cliente VARCHAR(20) NOT NULL,
Apellido_cliente_1 VARCHAR(20) NOT NULL,
Apellido_cliente_2 VARCHAR(20),
Edad VARCHAR(5),
Comunidad_autonoma VARCHAR(20),
Localidad VARCHAR(20),
Codigo_postal INT,
Direccion VARCHAR(30),
Telefono VARCHAR(20),
Email VARCHAR(20),
Contraseña VARBINARY(100) NOT NULL,
CONSTRAINT PRIMARY_KEY_CLIENTE PRIMARY KEY (DNI_Cliente)
);

CREATE TABLE TARJETA_CLIENTE ( 
Numero_tarjeta VARCHAR(16) NOT NULL,
DNI_cliente VARCHAR(9) NOT NULL,
Nombre_cliente VARCHAR(20) NOT NULL,
Fecha_caducidad VARCHAR(5) NOT NULL,
Tipo_tarjeta VARCHAR(10) NOT NULL,
CONSTRAINT PRIMARY_KEY_TARGETA_CLIENTE PRIMARY KEY (Numero_tarjeta),
CONSTRAINT FOREIGN_KEY_TARGETA_CLIENTE FOREIGN KEY (DNI_cliente) REFERENCES CLIENTE (DNI_Cliente)
);

CREATE TABLE SUPERMERCADO ( 
Codigo_supermercado INT NOT NULL,
NIF VARCHAR(9) NOT NULL,
Comunidad_autonoma VARCHAR(20),
Localidad VARCHAR(20),
Codigo_postal VARCHAR(5) NOT NULL,
Direccion VARCHAR(30) NOT NULL,
Telefono VARCHAR(20) NOT NULL,
Email VARCHAR(30),
Metros_cuadrados INT,
CONSTRAINT PRIMARY_KEY_SUPER PRIMARY KEY (Codigo_supermercado)
);

CREATE TABLE TICKET ( 
Codigo_ticket INT NOT NULL,
DNI_cliente VARCHAR(9) NOT NULL,
Codigo_supermercado INT NOT NULL,
Fecha_compra VARCHAR(20) NOT NULL,
Hora_compra VARCHAR(20) NOT NULL,
Precio_total DECIMAL(7,2) NOT NULL,
CONSTRAINT PRIMARY_KEY_TICKET PRIMARY KEY (Codigo_ticket),
CONSTRAINT FOREIGN_KEY_TICKET_DNI FOREIGN KEY (DNI_cliente) REFERENCES CLIENTE (DNI_Cliente),
CONSTRAINT FOREIGN_KEY_TICKET_CODIGO FOREIGN KEY (Codigo_supermercado) REFERENCES SUPERMERCADO (Codigo_supermercado)
);

CREATE TABLE PRODUCTO ( 
Codigo_producto INT NOT NULL,
Nombre_producto VARCHAR(20) NOT NULL,
Precio_producto DECIMAL(7,2) NOT NULL,
descripcionProd VARCHAR(300),
tipo_producto VARCHAR(20),
CONSTRAINT PRIMARY_KEY_CODPRODUCTO PRIMARY KEY (Codigo_producto)
);

CREATE TABLE PRODUCTO_ALIMENTO( ------------------------
    Codigo_producto INT NOT NULL,
    Caducidad INT,
    Categoria VARCHAR(20),
    CONSTRAINT PRIMARY_KEY_CODALIM PRIMARY KEY (Codigo_producto),
    CONSTRAINT FK_ALIMENTO FOREIGN KEY (Codigo_producto) REFERENCES PRODUCTO(Codigo_producto)
);

CREATE TABLE PRODUCTO_BEBIDA( --------------------------
    Codigo_producto INT NOT NULL,
    Caducidad INT,
    Alcoholica BOOLEAN,
    CONSTRAINT PRIMARY_KEY_CODBEB PRIMARY KEY (Codigo_producto),
    CONSTRAINT FK_BEBIDA FOREIGN KEY (Codigo_producto) REFERENCES PRODUCTO(Codigo_producto)
);

CREATE TABLE PRODUCTO_HIGIENE( 
    Codigo_producto INT NOT NULL,
    Tipo_higiene VARCHAR(20),
    CONSTRAINT PRIMARY_KEY_CODHIGIE PRIMARY KEY (Codigo_producto),
    CONSTRAINT FK_HIGIENE FOREIGN KEY (Codigo_producto) REFERENCES PRODUCTO(Codigo_producto)
);

CREATE TABLE PRODUCTO_LIMPIEZA( 
    Codigo_producto INT NOT NULL,
    Superficie VARCHAR(20),
    CONSTRAINT PRIMARY_KEY_CODLIMP PRIMARY KEY (Codigo_producto),
    CONSTRAINT FK_LIMPIEZA FOREIGN KEY (Codigo_producto) REFERENCES PRODUCTO(Codigo_producto)
);

CREATE TABLE LINEA_TICKET ( 
Codigo_ticket INT NOT NULL,
Codigo_producto INT NOT NULL,
Cantidad INT NOT NULL,
Precio DECIMAL(7,2),
CONSTRAINT PRIMARY_KEY_LINTICKET PRIMARY KEY (Codigo_ticket, Codigo_producto),
CONSTRAINT FOREIGN_KEY_CODTICK FOREIGN KEY (Codigo_ticket) REFERENCES TICKET (Codigo_ticket),
CONSTRAINT FOREIGN_KEY_CODPROD FOREIGN KEY (Codigo_producto) REFERENCES PRODUCTO (Codigo_producto)
);

CREATE TABLE STOCK_SUPERMERCADO ( 
Codigo_supermercado INT NOT NULL,
Codigo_producto INT NOT NULL,
Cantidad INT NOT NULL,
CONSTRAINT PRIMARY_KEY_STSUPER PRIMARY KEY (Codigo_supermercado, Codigo_producto),
CONSTRAINT FOREIGN_KEY_CODSUPER FOREIGN KEY (Codigo_supermercado) REFERENCES SUPERMERCADO (Codigo_supermercado),
CONSTRAINT FOREIGN_KEY_CODPRODUCTO FOREIGN KEY (Codigo_producto) REFERENCES PRODUCTO (Codigo_producto)
);

CREATE TABLE EMPLEADO ( 
ID_EMPLEADO INT NOT NULL,
Codigo_supermercado INT NOT NULL,
DNI_empleado VARCHAR(9) NOT NULL,
Nombre_empleado VARCHAR(10) NOT NULL,
Apellido_empleado_1 VARCHAR(20) NOT NULL,
Apellido_empleado_2 VARCHAR(20),
Edad INT,
Comunidad_autonoma VARCHAR(20) NOT NULL,
Localidad VARCHAR(20) NOT NULL,
Codigo_postal VARCHAR(20) NOT NULL,
Direccion VARCHAR(30) NOT NULL,
Telefono VARCHAR(20) NOT NULL,
Email VARCHAR(30),
Puesto_trabajo VARCHAR(20) NOT NULL,
Privilegios INT NOT NULL,
Contraseña VARBINARY(100) NOT NULL,
CONSTRAINT PRIMARY_KEY_EMPL PRIMARY KEY (ID_EMPLEADO),
CONSTRAINT FOREIGN_KEY_CODSUPEMPL FOREIGN KEY (Codigo_supermercado) REFERENCES SUPERMERCADO (Codigo_supermercado)
);

CREATE TABLE PLANTILLA_NOMINA ( 
Puesto_trabajo VARCHAR(20) NOT NULL,
Salario_base DECIMAL(7,2),
Hora_extra DECIMAL(4,2),
Nocturnidad DECIMAL(4,2),
CONSTRAINT PRIMARY_KEY_PLANTILLA_NOMINA PRIMARY KEY (Puesto_trabajo)
);

CREATE TABLE NOMINA ( 
Codigo_nomina INT NOT NULL,
ID_empleado INT NOT NULL,
Puesto_trabajo VARCHAR(20) NOT NULL,
Salario_base DECIMAL(7,2),
IRPF DECIMAL(3,1),
Fecha_inicio VARCHAR(20),
Fecha_fin VARCHAR(20),
Horas_extra_realizadas DECIMAL(3,1),
Horas_con_nocturnidad DECIMAL(3,1),
Salario_total DECIMAL(7,2),
CONSTRAINT PRIMARY_KEY_NOMINA PRIMARY KEY (Codigo_nomina),
CONSTRAINT FOREIGN_KEY_IDEMPL FOREIGN KEY (ID_empleado) REFERENCES EMPLEADO (ID_EMPLEADO),
CONSTRAINT FOREIGN_KEY_PLANTNOM FOREIGN KEY (Puesto_trabajo) REFERENCES PLANTILLA_NOMINA (Puesto_trabajo)
);

CREATE TABLE LINEA_CARRITO ( 
DNI_cliente VARCHAR(9) NOT NULL,
Codigo_producto INT NOT NULL,
Cantidad INT NOT NULL,
Precio DECIMAL(7,2),
CONSTRAINT PRIMARY_KEY_LINCARR PRIMARY KEY (DNI_cliente, Codigo_producto),
CONSTRAINT FOREIGN_KEY_CODCLIEN_CARR FOREIGN KEY (DNI_cliente) REFERENCES CLIENTE (DNI_cliente),
CONSTRAINT FOREIGN_KEY_CODPROD_CARR FOREIGN KEY (Codigo_producto) REFERENCES PRODUCTO (Codigo_producto)
);