/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafics;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import Main.Classes.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import Main.Classes.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jcanarte
 */
public class CrearTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form CrearTarjeta
     */
    public CrearTarjeta() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public JTextField getFechaCaducidad() {
        return fechaCaducidad;
    }

    public void setFechaCaducidad(JTextField fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }

    public JTextField getNumeroTarjeta() {
        return numeroTarjeta;
    }

    public void setNumeroTarjeta(JTextField numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }

    public JComboBox getTipoTarjeta() {
        return tipoTarjeta;
    }

    public void setTipoTarjeta(JComboBox tipoTarjeta) {
        this.tipoTarjeta = tipoTarjeta;
    }

    public JTextField getTitularTarjeta() {
        return titularTarjeta;
    }

    public void setTitularTarjeta(JTextField titularTarjeta) {
        this.titularTarjeta = titularTarjeta;
    }
    
    public Image getIconImage(){
        Image miIcono=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/2153422.png"));
        return miIcono;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        botonAtras = new javax.swing.JButton();
        numeroTarjeta = new javax.swing.JTextField();
        fechaCaducidad = new javax.swing.JTextField();
        titularTarjeta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tipoTarjeta = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        fondo1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(700, 376));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonAtras.setText("Atras");
        botonAtras.setToolTipText("");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 70, -1));
        getContentPane().add(numeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 200, -1));

        fechaCaducidad.setText("MM/YY");
        getContentPane().add(fechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 70, -1));
        getContentPane().add(titularTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 230, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Número");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha caducidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre titular");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo tarjeta");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        tipoTarjeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visa", "Mastercard", "American Express" }));
        getContentPane().add(tipoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 190, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Guardar Tarjeta");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 280, 40));

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, -1));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Green-Wallpaper-5.jpg"))); // NOI18N
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
    if(numeroTarjeta.getText().isEmpty() || titularTarjeta.getText().isEmpty() || fechaCaducidad.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "META SUS DATOS", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        numeroTarjeta.setText("");
        titularTarjeta.setText("");
        fechaCaducidad.setText("");
        numeroTarjeta.requestFocus();
        titularTarjeta.requestFocus();
        fechaCaducidad.requestFocus();
        tipoTarjeta.requestFocus();
    } else {
            PreparedStatement query=null;
            try {
                query=Herramientas.getConexion().prepareStatement(
                "Select COUNT(Numero_tarjeta) from TARJETA_CLIENTE where Numero_tarjeta=?");
                query.setString(1, this.getNumeroTarjeta().getText());
                ResultSet resultado=query.executeQuery();
                resultado.next();
                if(resultado.getInt(1) >= 1){
                    JOptionPane.showMessageDialog(this, "ESTA TARJETA YA EXISTE" , "Informacion", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    Tarjeta.añadirTarjeta(this.getNumeroTarjeta().getText(), this.getTitularTarjeta().getText(), 
                    this.getFechaCaducidad().getText(), this.getTipoTarjeta().getSelectedItem().toString());
                    numeroTarjeta.setText("");
                    titularTarjeta.setText("");
                    fechaCaducidad.setText("");
                    numeroTarjeta.requestFocus();
                    titularTarjeta.requestFocus();
                    fechaCaducidad.requestFocus();
                    JOptionPane.showMessageDialog(this, "LOS DATOS HAN SIGO GUARDADOS CORRECTAMENTE");
                }
            }catch (SQLException ex){
                Herramientas.aviso("Ha ocurrido un error al guardar su tarjeta");
                //Excepciones.pasarExcepcionLog("Ha ocurrido un error al guardar su tarjeta", ex);
                ex.printStackTrace();
            }
            finally{
                try {
                    query.close();
                } catch (SQLException ex) {
                    Herramientas.aviso("Ha ocurrido un error al guardar su tarjeta");
                    Excepciones.pasarExcepcionLog("Ha ocurrido un error al guardar su tarjeta", ex);
                }
            }
        }          
    }//GEN-LAST:event_botonGuardarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Herramientas.crearConexion();
                    new CrearTarjeta();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField fechaCaducidad;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField numeroTarjeta;
    private javax.swing.JComboBox tipoTarjeta;
    private javax.swing.JTextField titularTarjeta;
    // End of variables declaration//GEN-END:variables


}
