/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafics;

import Main.Classes.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class ElegirTarjeta extends javax.swing.JFrame {

    /**
     * Creates new form ElegirTarjeta
     */
    
    private ArrayList <Tarjeta> listaTarjetas;
    private InterfazUsuario3 interfaz;
    
    public ElegirTarjeta(InterfazUsuario3 interfaz) {
        initComponents();
        añadirTarjetas();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.setInterfaz(interfaz);
    }
    
    public Image getIconImage(){
        Image miIcono=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo1.png"));
        return miIcono;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tipoTarjeta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        numeroTarjeta = new javax.swing.JComboBox<>();
        fechaCaducidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nombreTarjeta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cvvField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        realizarCompra = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("  METRADONA©");
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(490, 320));
        setMinimumSize(new java.awt.Dimension(490, 320));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ELIGE UNA TARJETA PARA REALIZAR LA COMPRA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tipoTarjeta.setEditable(false);
        tipoTarjeta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(tipoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 195, 130, 35));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NUMERO TARJETA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 78, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NOMBRE TARJETA:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 121, -1, -1));

        numeroTarjeta.setBackground(new java.awt.Color(204, 204, 204));
        numeroTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        numeroTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(numeroTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 65, 240, 40));

        fechaCaducidad.setEditable(false);
        fechaCaducidad.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(fechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 153, 95, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CVV:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 156, -1, 27));

        nombreTarjeta.setEditable(false);
        nombreTarjeta.setBackground(new java.awt.Color(204, 204, 204));
        nombreTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(nombreTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 112, 242, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("FECHA CADUCIDAD:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 156, -1, 27));
        jPanel1.add(cvvField, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 153, 51, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("TIPO TARJETA:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 195, -1, 27));

        realizarCompra.setBackground(new java.awt.Color(102, 102, 102));
        realizarCompra.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        realizarCompra.setForeground(new java.awt.Color(255, 255, 255));
        realizarCompra.setText("REALIZAR COMPRA");
        realizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarCompraActionPerformed(evt);
            }
        });
        jPanel1.add(realizarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 310, 50));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Green-Wallpaper-5.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public InterfazUsuario3 getInterfaz() {
        return interfaz;
    }

    public void setInterfaz(InterfazUsuario3 interfaz) {
        this.interfaz = interfaz;
    }

    public JTextField getCvvField() {
        return cvvField;
    }

    public void setCvvField(JTextField cvvField) {
        this.cvvField = cvvField;
    }
    
    

    private void nombreTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTarjetaActionPerformed

    private void realizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarCompraActionPerformed
        try {
            if(this.getCvvField().getText().isBlank() || 
            this.getCvvField().getText().length()!=3){
                throw new Excepciones(4);
            }
            int esNumerico=Integer.parseInt(this.getCvvField().getText());
            Main.getClienteActivo().confirmarCompra();
            this.getInterfaz().escribirListaCompra(Main.getClienteActivo().getCestaCompra());
            Herramientas.aviso("COMPRA REALIZADA!");
            this.dispose();
        } catch (SQLException ex) {
            Herramientas.aviso("Ha habido un error al procesar su compra");
            Excepciones.pasarExcepcionLog("Ha habido un error al procesar su compra", ex);
        } catch (Excepciones ex) {
            Herramientas.aviso(ex.getMessage());
            Excepciones.pasarExcepcionLog(ex.getMessage(), ex);
        } catch (NumberFormatException ex) {
            Herramientas.aviso("Inserte un cvv correcto");
            Excepciones.pasarExcepcionLog("Inserte un cvv correcto", ex);
        }
    }//GEN-LAST:event_realizarCompraActionPerformed

    private void numeroTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTarjetaActionPerformed
        this.añadiDatos();
    }//GEN-LAST:event_numeroTarjetaActionPerformed

    public ArrayList<Tarjeta> getListaTarjetas() {
        return listaTarjetas;
    }

    public void setListaTarjetas(ArrayList<Tarjeta> listaTarjetas) {
        this.listaTarjetas = listaTarjetas;
    }
    
    public void añadirTarjetas(){
        try {
            this.setListaTarjetas(Tarjeta.recogerTarjeta(Main.getClienteActivo().getNif()));
            String[] listaNumerosTarjeta=new String[this.getListaTarjetas().size()];
            for(int i=0;i<this.getListaTarjetas().size();i++){
                listaNumerosTarjeta[i]=this.getListaTarjetas().get(i).getNumero();
            }
            numeroTarjeta.setModel(new javax.swing.DefaultComboBoxModel<>(listaNumerosTarjeta));
            this.añadiDatos();
        } catch (SQLException ex) {
            Herramientas.aviso("Ha ocurrido un error al cargar su tarjetas");
            Excepciones.pasarExcepcionLog("Ha ocurrido un error al cargar su tarjetas", ex);
            this.dispose();
        }
    }
    
    public void añadiDatos(){
        this.nombreTarjeta.setText(this.getListaTarjetas().get(this.numeroTarjeta.getSelectedIndex()).getNombre_tarjeta());
        this.fechaCaducidad.setText(this.getListaTarjetas().get(this.numeroTarjeta.getSelectedIndex()).getFecha_caducidad());
        this.tipoTarjeta.setText(this.getListaTarjetas().get(this.numeroTarjeta.getSelectedIndex()).getTipo_tarjeta());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cvvField;
    private javax.swing.JTextField fechaCaducidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreTarjeta;
    private javax.swing.JComboBox<String> numeroTarjeta;
    private javax.swing.JButton realizarCompra;
    private javax.swing.JTextField tipoTarjeta;
    // End of variables declaration//GEN-END:variables
}
