/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafics;

import Main.Classes.Herramientas;
import javax.swing.JList;
import javax.swing.JOptionPane;
import Main.Classes.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 *
 * @author jaume
 */
public class ElegirSupermercado extends javax.swing.JFrame {
    
    private InicioSesion login;
    /**
     * Creates new form ElegirSupermercado
     */
    public ElegirSupermercado() {
        initComponents();
        this.añadirSupermercados();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    
    public ElegirSupermercado(InicioSesion login) {
        initComponents();
        this.añadirSupermercados();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.login=login;
    }

    public JList<String> getListaSupermercados() {
        return listaSupermercados;
    }
    
    public Image getIconImage(){
        Image miIcono=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/logo1.png"));
        return miIcono;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollSupermercados = new javax.swing.JScrollPane();
        listaSupermercados = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        Elegir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("  METRADONA©");
        setIconImage(getIconImage());
        setUndecorated(true);

        listaSupermercados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listaSupermercados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Metradona Barcelona", "Metradona Las Plamas de Gran Canaria", "Metradona Madrid", "Metradona Mallorca", "Metradona Sevilla" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaSupermercados.setSelectionBackground(new java.awt.Color(51, 153, 0));
        scrollSupermercados.setViewportView(listaSupermercados);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Elige un supermercado");

        Elegir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Elegir.setText("Elegir");
        Elegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElegirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollSupermercados, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(Elegir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(scrollSupermercados, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Elegir, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElegirActionPerformed
        try{
            String supermercado=this.getListaSupermercados().getSelectedValue();
            if (supermercado==null){
                Herramientas.aviso("Elige un supermercado primero");
            }
            else{
                int codigoSupermercado=Integer.parseInt(supermercado.split("-")[0]);
                Main.setSupermercadoActivo(Supermercado.instantiateSupermarketFromDB(codigoSupermercado));
                InterfazUsuario3 programa=new InterfazUsuario3();
                login.dispose();
                this.dispose();
            }
        }
        catch(SQLException ex){
            Herramientas.aviso("Ha habido un problema al seleccionar el Supermercado");
            Excepciones.pasarExcepcionLog("Ha habido un problema al seleccionar el Supermercado", ex);
        }
    }//GEN-LAST:event_ElegirActionPerformed
    
    public void añadirSupermercados(){
        ArrayList <String> listaSupers=Supermercado.getSupermarketsFromDatabase();
        String[] supermercados=new String[listaSupers.size()];
        for (int i=0; i<listaSupers.size();i++){
            supermercados[i]=listaSupers.get(i)+" METRADONA";
        }
        listaSupermercados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] arraysSupermercados=supermercados;
            public int getSize() { return arraysSupermercados.length; }
            public String getElementAt(int i) { return arraysSupermercados[i]; }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Elegir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> listaSupermercados;
    private javax.swing.JScrollPane scrollSupermercados;
    // End of variables declaration//GEN-END:variables



}
