/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafics;

import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import Main.Classes.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author PC
 */
public class InterfazUsuario3 extends javax.swing.JFrame {
    
    private JComponent panelActivo;
    private JPanel panelCabezeraActivo;
    
    /**
     * Creates new form InterfazUsuario
     */
    public InterfazUsuario3(){
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        try {
            //Herramientas.crearConexion();
            this.escribirListaCompra(new ArrayList());
        } catch (SQLException ex) {
            Herramientas.aviso("Ha habido un error con la base de datos, no se ha podido cargar su lista de compra");
        }
        this.getCestaCompra().setVisible(false);
        this.getjScrollPane1().setVisible(false);
        this.nombre.setText(Main.getClienteActivo().getNombre().toUpperCase());
        this.setPanelActivo(panelInicial);
        this.setPanelCabezeraActivo(cabezeraInicial);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cabezeraAlimento = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cabezeraBebida = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cabezeraHigiene = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cabezeraLimpieza = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        scrollAlimento = new javax.swing.JScrollPane();
        panelAlimento = new javax.swing.JPanel();
        scrollBebida = new javax.swing.JScrollPane();
        panelBebida = new javax.swing.JPanel();
        scrollHigiene = new javax.swing.JScrollPane();
        panelHigiene = new javax.swing.JPanel();
        scrollLimpieza = new javax.swing.JScrollPane();
        panelLimpieza = new javax.swing.JPanel();
        lineaProductoAlimento = new javax.swing.JPanel();
        nombreProducto = new javax.swing.JLabel();
        precioProducto = new javax.swing.JLabel();
        descripcionProducto = new javax.swing.JLabel();
        botonAñadir = new javax.swing.JButton();
        cantidad = new javax.swing.JSpinner();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        alimento = new javax.swing.JButton();
        bebida = new javax.swing.JButton();
        botonCarrito = new javax.swing.JLabel();
        higiene = new javax.swing.JButton();
        limpieza = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cestaCompra = new javax.swing.JPanel();
        panelInicial = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cabezeraInicial = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        cabezeraAlimento.setBackground(new java.awt.Color(255, 255, 255));
        cabezeraAlimento.setPreferredSize(new java.awt.Dimension(702, 163));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel13.setText("ALIMENTOS");

        javax.swing.GroupLayout cabezeraAlimentoLayout = new javax.swing.GroupLayout(cabezeraAlimento);
        cabezeraAlimento.setLayout(cabezeraAlimentoLayout);
        cabezeraAlimentoLayout.setHorizontalGroup(
            cabezeraAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 702, Short.MAX_VALUE)
            .addGroup(cabezeraAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cabezeraAlimentoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        cabezeraAlimentoLayout.setVerticalGroup(
            cabezeraAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 163, Short.MAX_VALUE)
            .addGroup(cabezeraAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(cabezeraAlimentoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        cabezeraBebida.setBackground(new java.awt.Color(255, 255, 255));
        cabezeraBebida.setPreferredSize(new java.awt.Dimension(702, 163));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel10.setText("BEBIDAS");

        javax.swing.GroupLayout cabezeraBebidaLayout = new javax.swing.GroupLayout(cabezeraBebida);
        cabezeraBebida.setLayout(cabezeraBebidaLayout);
        cabezeraBebidaLayout.setHorizontalGroup(
            cabezeraBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraBebidaLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel10)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        cabezeraBebidaLayout.setVerticalGroup(
            cabezeraBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraBebidaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        cabezeraHigiene.setBackground(new java.awt.Color(255, 255, 255));
        cabezeraHigiene.setPreferredSize(new java.awt.Dimension(702, 163));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel11.setText("HIGIENE");

        javax.swing.GroupLayout cabezeraHigieneLayout = new javax.swing.GroupLayout(cabezeraHigiene);
        cabezeraHigiene.setLayout(cabezeraHigieneLayout);
        cabezeraHigieneLayout.setHorizontalGroup(
            cabezeraHigieneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraHigieneLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel11)
                .addContainerGap(195, Short.MAX_VALUE))
        );
        cabezeraHigieneLayout.setVerticalGroup(
            cabezeraHigieneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraHigieneLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel11)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        cabezeraLimpieza.setBackground(new java.awt.Color(255, 255, 255));
        cabezeraLimpieza.setPreferredSize(new java.awt.Dimension(702, 163));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        jLabel12.setText("LIMPIEZA");

        javax.swing.GroupLayout cabezeraLimpiezaLayout = new javax.swing.GroupLayout(cabezeraLimpieza);
        cabezeraLimpieza.setLayout(cabezeraLimpiezaLayout);
        cabezeraLimpiezaLayout.setHorizontalGroup(
            cabezeraLimpiezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraLimpiezaLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel12)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        cabezeraLimpiezaLayout.setVerticalGroup(
            cabezeraLimpiezaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraLimpiezaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        scrollAlimento.setPreferredSize(new java.awt.Dimension(1200, 375));

        panelAlimento.setBackground(new java.awt.Color(255, 255, 255));
        panelAlimento.setMaximumSize(new java.awt.Dimension(0, 0));
        panelAlimento.setLayout(new javax.swing.BoxLayout(panelAlimento, javax.swing.BoxLayout.Y_AXIS));
        scrollAlimento.setViewportView(panelAlimento);

        scrollBebida.setPreferredSize(new java.awt.Dimension(1200, 375));

        panelBebida.setBackground(new java.awt.Color(255, 255, 255));
        panelBebida.setMaximumSize(new java.awt.Dimension(0, 0));
        panelBebida.setMinimumSize(new java.awt.Dimension(0, 0));
        panelBebida.setName(""); // NOI18N
        panelBebida.setLayout(new javax.swing.BoxLayout(panelBebida, javax.swing.BoxLayout.Y_AXIS));
        scrollBebida.setViewportView(panelBebida);

        scrollHigiene.setPreferredSize(new java.awt.Dimension(1200, 375));

        panelHigiene.setBackground(new java.awt.Color(255, 255, 255));
        panelHigiene.setMaximumSize(new java.awt.Dimension(0, 0));
        panelHigiene.setLayout(new javax.swing.BoxLayout(panelHigiene, javax.swing.BoxLayout.Y_AXIS));
        scrollHigiene.setViewportView(panelHigiene);

        scrollLimpieza.setPreferredSize(new java.awt.Dimension(1200, 375));

        panelLimpieza.setBackground(new java.awt.Color(255, 255, 255));
        panelLimpieza.setMaximumSize(new java.awt.Dimension(0, 0));
        panelLimpieza.setLayout(new javax.swing.BoxLayout(panelLimpieza, javax.swing.BoxLayout.Y_AXIS));
        scrollLimpieza.setViewportView(panelLimpieza);

        lineaProductoAlimento.setBackground(new java.awt.Color(255, 255, 255));
        lineaProductoAlimento.setMaximumSize(new java.awt.Dimension(1100, 50));
        lineaProductoAlimento.setMinimumSize(new java.awt.Dimension(1100, 50));
        lineaProductoAlimento.setPreferredSize(new java.awt.Dimension(1100, 50));

        nombreProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombreProducto.setText("Macarrones");

        precioProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        precioProducto.setText("Precio: 3,5");
        precioProducto.setPreferredSize(new java.awt.Dimension(70, 14));

        descripcionProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descripcionProducto.setText("Macarrones traidos desde italia, con la receta tipica siciliana de pasta fresca de la mia mamma");

        botonAñadir.setText("AÑADIR");

        cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));

        javax.swing.GroupLayout lineaProductoAlimentoLayout = new javax.swing.GroupLayout(lineaProductoAlimento);
        lineaProductoAlimento.setLayout(lineaProductoAlimentoLayout);
        lineaProductoAlimentoLayout.setHorizontalGroup(
            lineaProductoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineaProductoAlimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
        );
        lineaProductoAlimentoLayout.setVerticalGroup(
            lineaProductoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineaProductoAlimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lineaProductoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidad)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAñadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("  METRADONA©");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1200, 700));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(1200, 168));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(51, 153, 0));
        titulo.setText("METRADONA");
        titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tituloMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));

        alimento.setBackground(new java.awt.Color(255, 255, 255));
        alimento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        alimento.setForeground(new java.awt.Color(255, 255, 255));
        alimento.setText("ALIMENTO");
        alimento.setBorder(null);
        alimento.setBorderPainted(false);
        alimento.setContentAreaFilled(false);
        alimento.setFocusPainted(false);
        alimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentoActionPerformed(evt);
            }
        });

        bebida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bebida.setForeground(new java.awt.Color(255, 255, 255));
        bebida.setText("BEBIDA");
        bebida.setContentAreaFilled(false);
        bebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidaActionPerformed(evt);
            }
        });

        botonCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cestajpg.jpg"))); // NOI18N
        botonCarrito.setToolTipText("Carrito de compra");
        botonCarrito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCarritoMouseClicked(evt);
            }
        });

        higiene.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        higiene.setForeground(new java.awt.Color(255, 255, 255));
        higiene.setText("HIGIENE");
        higiene.setContentAreaFilled(false);
        higiene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higieneActionPerformed(evt);
            }
        });

        limpieza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        limpieza.setForeground(new java.awt.Color(255, 255, 255));
        limpieza.setText("LIMPIEZA");
        limpieza.setContentAreaFilled(false);
        limpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiezaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(alimento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(higiene, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(limpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCarrito)
                .addGap(160, 160, 160))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(bebida, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(alimento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(higiene, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(limpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(botonCarrito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(306, 183));

        cestaCompra.setBackground(new java.awt.Color(255, 255, 255));
        cestaCompra.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        cestaCompra.setMaximumSize(new java.awt.Dimension(0, 0));
        cestaCompra.setMinimumSize(new java.awt.Dimension(0, 0));
        cestaCompra.setRequestFocusEnabled(false);
        cestaCompra.setLayout(new javax.swing.BoxLayout(cestaCompra, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(cestaCompra);

        panelInicial.setBackground(new java.awt.Color(255, 255, 255));
        panelInicial.setPreferredSize(new java.awt.Dimension(1200, 375));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alimentos.jpg"))); // NOI18N
        panelInicial.add(jLabel8);

        cabezeraInicial.setBackground(new java.awt.Color(255, 255, 255));
        cabezeraInicial.setPreferredSize(new java.awt.Dimension(702, 163));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        jLabel4.setText("BIENVENIDO ");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setText("ENCUENTRE LOS MEJORES PRODUCTOS");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel14.setText("EN SU SUPERMERCADO DE CONFIANZA");

        nombre.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        nombre.setForeground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout cabezeraInicialLayout = new javax.swing.GroupLayout(cabezeraInicial);
        cabezeraInicial.setLayout(cabezeraInicialLayout);
        cabezeraInicialLayout.setHorizontalGroup(
            cabezeraInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraInicialLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(cabezeraInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9)
                    .addGroup(cabezeraInicialLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        cabezeraInicialLayout.setVerticalGroup(
            cabezeraInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cabezeraInicialLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cabezeraInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cabezeraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addComponent(panelInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cabezeraInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.setLayer(panelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCarritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCarritoMouseClicked
        try {
            this.escribirListaCompra(Main.getClienteActivo().getCestaCompra());
        } catch (SQLException ex) {
            System.out.println("surt");
        }
        if (this.getCestaCompra().isVisible()){
            this.getCestaCompra().setVisible(false);
            this.getjScrollPane1().setVisible(false);
        }
        else{
            this.getCestaCompra().setVisible(true);
            this.getjScrollPane1().setVisible(true);
        }
        this.revalidate();
        this.repaint();
        System.out.println("hola");
    }//GEN-LAST:event_botonCarritoMouseClicked

    private void bebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidaActionPerformed
        try {
            panelBebida.removeAll();
            this.obtenerStock(panelBebida,"Bebida");
            this.cambiarPanel(scrollBebida, cabezeraBebida);
        } catch (SQLException ex) {
            Herramientas.aviso("Hay un problema con el stock en la base de datos, lo sentimos");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bebidaActionPerformed

    private void alimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentoActionPerformed
        try {
            panelAlimento.removeAll();
            this.obtenerStock(panelAlimento,"Alimento");
            this.cambiarPanel(scrollAlimento, cabezeraAlimento);
        } catch (SQLException ex) {
            Herramientas.aviso("Hay un problema con el stock en la base de datos, lo sentimos");
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_alimentoActionPerformed

    private void tituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tituloMouseClicked
        this.cambiarPanel(panelInicial, cabezeraInicial);
    }//GEN-LAST:event_tituloMouseClicked

    private void higieneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higieneActionPerformed
        try {
            panelHigiene.removeAll();
            this.obtenerStock(panelHigiene,"Higiene");
            this.cambiarPanel(scrollHigiene, cabezeraHigiene);
        } catch (SQLException ex) {
            Herramientas.aviso("Hay un problema con el stock en la base de datos, lo sentimos");
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_higieneActionPerformed

    private void limpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiezaActionPerformed
        try {
            panelLimpieza.removeAll();
            this.obtenerStock(panelLimpieza,"Limpieza");
            this.cambiarPanel(scrollLimpieza, cabezeraLimpieza);
        } catch (SQLException ex) {
            Herramientas.aviso("Hay un problema con el stock en la base de datos, lo sentimos");
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_limpiezaActionPerformed

    private void logoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoMouseClicked
        this.cambiarPanel(panelInicial, cabezeraInicial);
    }//GEN-LAST:event_logoMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Herramientas.getConexion().close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowClosing

    public JComponent getPanelActivo() {
        return panelActivo;
    }

    public void setPanelActivo(JComponent panelActivo) {
        this.panelActivo = panelActivo;
    }

    public JPanel getPanelCabezeraActivo() {
        return panelCabezeraActivo;
    }

    public void setPanelCabezeraActivo(JPanel panelCabezeraActivo) {
        this.panelCabezeraActivo = panelCabezeraActivo;
    }
    
    
    public JPanel getCestaCompra() {
        return cestaCompra;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }
    //Main.getClienteActivo().getCestaCompra()
    public void escribirListaCompra(ArrayList <LineaCompra> cesta) throws SQLException{
        this.getCestaCompra().removeAll();
        if (cesta.isEmpty()){
            JLabel info1=new JLabel(" ");
            JLabel info=new JLabel("            NO HAY PRODUCTOS EN SU CESTA      ");
            info.setFont(new Font("Tahoma",Font.BOLD,12));
            this.getCestaCompra().add(info1);
            this.getCestaCompra().add(info);
        }
        else{
            JLabel cabecera=new JLabel("PRODUCTO        CANTIDAD           PRECIO");
            cabecera.setFont(new Font("Tahoma",Font.BOLD,12));
            this.getCestaCompra().add(cabecera);
            for (int i=0; i<cesta.size();i++){
                Herramientas.hacerSelect("SELECT nombre_producto FROM producto WHERE codigo_producto="+cesta.get(i).getCodigo_producto()+"", true);
                ResultSet resultado=Herramientas.getResultado();
                resultado.next();
                JLabel lineacarrito=new JLabel(resultado.getString(1)+"        "+cesta.get(i).getCantidad()+"                 "+cesta.get(i).getPrecio_linea());
                Herramientas.cerrarStatementResult();
                lineacarrito.setFont(new Font("Tahoma",Font.PLAIN,12));
                this.getCestaCompra().add(lineacarrito);
            }
        }
        this.getCestaCompra().revalidate();
        this.getCestaCompra().repaint();

    }
    
    public void cambiarPanel(javax.swing.JComponent panel, javax.swing.JPanel cabezera){
        this.panelPrincipal.remove(this.getPanelActivo());
        this.panelPrincipal.remove(this.getPanelCabezeraActivo());
        this.añadirPanel(panel, cabezera);
        this.setPanelActivo(panel);
        this.setPanelCabezeraActivo(cabezera);
        this.revalidate();
        this.repaint();
    }
    
    public void añadirPanel(javax.swing.JComponent panel, javax.swing.JPanel cabezera){
        
        panel.setPreferredSize(new java.awt.Dimension(1200, 375));
        
        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(cabezera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cabezera, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    } 
    
    public void crearLineaCompra(javax.swing.JPanel panel, String nombre, double precio, String descripcion, int cantidadProducto, int codigoProducto){
        
        javax.swing.JLabel nombreProducto=new javax.swing.JLabel();
        javax.swing.JLabel precioProducto=new javax.swing.JLabel();
        javax.swing.JLabel descripcionProducto=new javax.swing.JLabel();
        javax.swing.JButton botonAñadir=new javax.swing.JButton();
        javax.swing.JSpinner cantidad=new javax.swing.JSpinner();
        javax.swing.JPanel lineaProductoAlimento=new javax.swing.JPanel();
        
        lineaProductoAlimento.setBackground(new java.awt.Color(255, 255, 255));
        lineaProductoAlimento.setMaximumSize(new java.awt.Dimension(1100, 50));
        lineaProductoAlimento.setMinimumSize(new java.awt.Dimension(1100, 50));
        lineaProductoAlimento.setPreferredSize(new java.awt.Dimension(1100, 50));
        lineaProductoAlimento.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 0)));
        nombreProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nombreProducto.setText(nombre);

        precioProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        precioProducto.setText("Precio: "+precio);
        precioProducto.setPreferredSize(new java.awt.Dimension(70, 14));

        descripcionProducto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        descripcionProducto.setText(descripcion);
        
        InterfazUsuario3 frame=this;
        
        botonAñadir.setText("AÑADIR");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main.getClienteActivo().añadirProductoCarrito(codigoProducto, precio,((int)cantidad.getValue()));
                try {
                    frame.escribirListaCompra(Main.getClienteActivo().getCestaCompra());
                } catch (SQLException ex) {
                    Herramientas.aviso("Error con la cesta en la base de datos");
                    ex.printStackTrace();
                }
            }
        });

        cantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, cantidadProducto, 1));

        javax.swing.GroupLayout lineaProductoAlimentoLayout = new javax.swing.GroupLayout(lineaProductoAlimento);
        lineaProductoAlimento.setLayout(lineaProductoAlimentoLayout);
        lineaProductoAlimentoLayout.setHorizontalGroup(
            lineaProductoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineaProductoAlimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(precioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
        );
        lineaProductoAlimentoLayout.setVerticalGroup(
            lineaProductoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lineaProductoAlimentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lineaProductoAlimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cantidad)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(precioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAñadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descripcionProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        
        panel.add(lineaProductoAlimento);
        lineaProductoAlimento.setVisible(true);
    }
    
    public void obtenerStock(javax.swing.JPanel panel,String tipoProducto) throws SQLException{
        ArrayList <StockProducto> stock=Main.getSupermercadoActivo().getStockSupermercado();
        PreparedStatement query=null;
        ResultSet resultado=null;
        try{
            for (int i=0; i<stock.size(); i++){
                query=Herramientas.getConexion().prepareStatement("SELECT * FROM producto WHERE codigo_producto=? AND tipo_producto=?");
                query.setInt(1,stock.get(i).getCodigoProducto());
                query.setString(2, tipoProducto);
                resultado=query.executeQuery();
                if (resultado.next()) {
                    this.crearLineaCompra(panel,resultado.getString("nombre_producto"),
                    resultado.getDouble("precio_producto"),resultado.getString("descripcionProd"),
                    stock.get(i).getCantidad(), resultado.getInt("codigo_producto"));
                }
            }
        }
        catch(SQLException ex){
            Herramientas.aviso("Se ha producido un error al cargar el stock");
            ex.printStackTrace();
        }
        finally{
            resultado.close();
            query.close();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazUsuario3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alimento;
    private javax.swing.JButton bebida;
    private javax.swing.JButton botonAñadir;
    private javax.swing.JLabel botonCarrito;
    private javax.swing.JPanel cabezeraAlimento;
    private javax.swing.JPanel cabezeraBebida;
    private javax.swing.JPanel cabezeraHigiene;
    private javax.swing.JPanel cabezeraInicial;
    private javax.swing.JPanel cabezeraLimpieza;
    private javax.swing.JSpinner cantidad;
    private javax.swing.JPanel cestaCompra;
    private javax.swing.JLabel descripcionProducto;
    private javax.swing.JButton higiene;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpieza;
    private javax.swing.JPanel lineaProductoAlimento;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombreProducto;
    private javax.swing.JPanel panelAlimento;
    private javax.swing.JPanel panelBebida;
    private javax.swing.JPanel panelHigiene;
    private javax.swing.JPanel panelInicial;
    private javax.swing.JPanel panelLimpieza;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel precioProducto;
    private javax.swing.JScrollPane scrollAlimento;
    private javax.swing.JScrollPane scrollBebida;
    private javax.swing.JScrollPane scrollHigiene;
    private javax.swing.JScrollPane scrollLimpieza;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
